<?php
require_once 'PHPUnit/Framework.php';

require_once 'test.controller.php';
require_once dirname(__FILE__).'/../../../../../objects/page/abstractResponse.class.php';
require_once dirname(__FILE__).'/../../../../../src/http/Request.class.php';
require_once dirname(__FILE__).'/../../../../../src/http/Response.class.php';

/**
 * Test class for test.
 * Generated by PHPUnit on 2011-01-06 at 21:05:25.
 */
class testTest extends PHPUnit_Framework_TestCase
{
    /** @var test */
    protected $controller;
    /** @var Request */
    protected $request;
    /** @var Response */
    protected $response;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->controller = new test;

        $requestStub = $this->getMock('Request');
        $requestStub->expects($this->any())
            ->method('getAction')
            ->will($this->returnValue('index'));

        $this->request = $requestStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testIndex()
    {
        $responseStub = $this->getMock('Response');
        $responseStub->expects($this->once())
            ->method('setTitle')
            ->with('Test');

        $this->controller->index($this->request, $responseStub);
    }
}
?>
