language: php
php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - npm install -g bower
  - npm install -g grunt-cli

install:
  - composer install
  - sh test/mockProject/install-dependencies.sh

script: vendor/bin/phing

after_script: php vendor/bin/coveralls -v

sudo: false