<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../objects/dependantObject.class.php';

/**
 * Test class for DependantObject.
 * Generated by PHPUnit on 2011-01-14 at 17:43:08.
 */
class DependantObjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DependantObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('DependantObject');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testStyleSheet()
    {
        $sheet = 'sheet';
        $this->object->addStyleSheet($sheet);
        $this->assertSame(array($sheet), $this->object->getStyles());
    }

    public function testJavaScript()
    {
        $js = 'js';
        $this->object->addJavaScript($js);
        $this->assertSame(array($js), $this->object->getJavaScripts());
    }

    public function testAddJsInit()
    {
        $jsInit = 'jsInit';
        $this->object->addJsInit($jsInit);
        $this->assertSame(array($jsInit), $this->object->getJsInits());
    }

    public function testTemplate()
    {
        $template = 'template';
        $this->object->setTemplate($template);
        $this->assertSame($template, $this->object->getTemplate());
    }

    public function testGetDependencies()
    {
        $sheet = 'sheet';
        $this->object->addStyleSheet($sheet);
        $js = 'js';
        $this->object->addJavaScript($js);
        $jsInit = 'jsInit';
        $this->object->addJsInit($jsInit);
        $this->assertSame(
            array(
                 'scripts' => array($js),
                 'jsInits' => array($jsInit),
                 'styles'  => array($sheet)
            ),
            $this->object->getDependencies()
        );
    }
}
