<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../../src/components/form/inputs/DateInput.php';

/**
 * Test class for DateInput.
 * Generated by PHPUnit on 2011-01-26 at 18:30:53.
 */
class DateInputTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DateInput
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DateInput;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testDefaultInit()
    {
        $this->assertSame('date', $this->object->getType());
        $this->assertSame('textInput datepicker', $this->object->getClass());
        $this->assertSame(array('jqueryUi'), $this->object->getJavaScripts());
        $this->assertSame(
            array(
                 "$('input.datepicker').datepicker({
                dateFormat: 'yy-mm-dd',
                buttonImage: '/resources/shared/img/calendar.gif',
                buttonImageOnly: true, showOn: 'both'
            });"
            ),
            $this->object->getJsInits()
        );
    }
}
?>
