<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../../src/components/form/inputs/FileInput.php';

/**
 * Test class for FileInput.
 * Generated by PHPUnit on 2011-01-25 at 22:01:22.
 */
class FileInputTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FileInput
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileInput;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testClassName()
    {
        $this->assertSame('fileInput', $this->object->getClass());
    }

    public function testType()
    {
        $this->assertSame('file', $this->object->getType());
    }

    public function testTemplate()
    {
        $this->assertSame('components/form/inputWithLabel.tpl', $this->object->getTemplate());
    }
}
?>
