<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/src/components/form/inputs/Input.php';

/**
 * Test class for Input.
 * Generated by PHPUnit on 2011-01-25 at 21:26:06.
 */
class InputTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Input
     */
    protected $input;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $options = array();
        $options['label'] = 'label';
        $options['value'] = 'value';
        $options['validations'] = array('validation1', 'validation2');

        $this->input = $this->getMockForAbstractClass('Input', array($options));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testAddValidation().
     */
    public function testAddValidation()
    {
        $this->input->addValidation('validation3');

        $this->assertSame(array('validation1', 'validation2', 'validation3'), $this->input->getValidations());
    }

    public function testGetName()
    {
        $this->assertSame('label', $this->input->getName());
    }

    public function testGetLabel()
    {
        $this->assertSame('label', $this->input->getLabel());
    }

    public function testGetType()
    {
        $this->assertSame(null, $this->input->getType());
    }

    public function testGetValue()
    {
        $this->assertSame('value', $this->input->getValue());
    }

    public function testGetClass()
    {
        $this->assertSame(null, $this->input->getClass());
    }

    public function testGetValidations()
    {
       $this->assertSame(array('validation1', 'validation2'), $this->input->getValidations());
    }
}
?>
