<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../../src/components/form/inputs/TextArea.php';

/**
 * Test class for TextArea.
 * Generated by PHPUnit on 2011-01-26 at 17:28:35.
 */
class TextAreaTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TextArea
     */
    protected $textArea;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $options = array();
        $options['rows'] = 4;

        $this->textArea = new TextArea($options);
    }

    public function testGetRows()
    {
        $this->assertSame(4, $this->textArea->getRows());
    }

    public function testGetRowsDefault()
    {
        $textArea = new TextArea(array());

        $this->assertEquals(null, $textArea->getRows());
    }

    public function testClassName()
    {
        $this->assertSame('textInput', $this->textArea->getClass());
    }

    public function testType()
    {
        $this->assertNull($this->textArea->getType());
    }

    public function testTemplate()
    {
        $this->assertSame('components/form/textArea.tpl', $this->textArea->getTemplate());
    }
}
?>
