<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../../src/components/form/inputs/TextArea.php';

/**
 * Test class for TextArea.
 * Generated by PHPUnit on 2011-01-26 at 17:28:35.
 */
class TextAreaTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TextArea
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $options = array();
        $options['rows'] = 4;

        $this->object = new TextArea($options);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetRows().
     */
    public function testGetRows()
    {
        $this->assertSame(4, $this->object->getRows());
    }

    /**
     * @todo Implement testGetRowsDefault().
     */
    public function testGetRowsDefault()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    public function testClassName()
    {
        $this->assertSame('textInput', $this->object->getClass());
    }

    public function testType()
    {
        $this->assertNull($this->object->getType());
    }

    public function testTemplate()
    {
        $this->assertSame('components/form/textArea.tpl', $this->object->getTemplate());
    }
}
?>
