<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/src/controller/abstract.controller.php';
require_once '/home/travi/include/php/framework/src/http/Request.class.php';
require_once '/home/travi/include/php/framework/src/exception/NotFound.exception.php';

/**
 * Test class for AbstractController.
 * Generated by PHPUnit on 2011-01-08 at 19:27:50.
 */
class AbstractControllerTest extends PHPUnit_Framework_TestCase
{
    /** @var AbstractController */
    protected $controller;
    /** @var Request */
    protected $requestStub;
    /** @var Response */
    protected $responseStub;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->controller = $this->getMockForAbstractClass('AbstractController');

        $requestStub = $this->getMock('Request');
        $requestStub->expects($this->any())
            ->method('getController')
            ->will($this->returnValue('test'));
        $requestStub->expects($this->any())
            ->method('getAction')
            ->will($this->returnValue('index'));
        $this->requestStub = $requestStub;

        $this->responseStub = $this->getMock('Response');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @expectedException NotFoundException
     */
    public function testDoAction()
    {
        $this->controller->doAction($this->requestStub, $this->responseStub);
    }
}
?>
