#=======Framework Components=======
framework:
  local: /resources/thirdparty/travi-core/dist/travi-core.min.js
  jsDependencies:
    - jquery
    - amplify
    - jsRender
  clientTemplates:
    chooseEnhancement: /resources/thirdparty/travi-core/templates/enhancementVersion.tmpl

pagination:
  local: /resources/thirdparty/travi-ui/js/pagination.js
  jsDependencies:
    - events
    - dependencyChecker

dialog:
  local: /resources/thirdparty/travi-ui/js/dialog/conventions.js
  jsDependencies:
    - /resources/thirdparty/travi-ui/js/dialog/events.js
    - /resources/thirdparty/travi-ui/js/dialog/core.js
    - /resources/thirdparty/travi-ui/js/form/validationMapper.js
    - /resources/thirdparty/travi-ui/js/dialog/form.js

entityList:
  local: /resources/thirdparty/travi-ui/js/entityList.js
  jsDependencies:
    - jqueryUi
    - ajaxForm
    - framework
    - pagination
  cssDependencies:
    - /resources/thirdparty/travi-styles/css/travi-entities.css
  clientTemplates:
    update-item: /resources/thirdparty/travi-core/templates/entity-item.tmpl
  large:
    local: /resources/thirdparty/travi-ui/js/entityList/pagination.js
    jsDependencies:
      - richTextArea
      - dialog
      - datePicker
      - buttons
      - /resources/thirdparty/travi-ui/js/entityList/updates.js
      - /resources/thirdparty/travi-ui/js/dialog/richText.js
      - /resources/thirdparty/travi-ui/js/dialog/date.js
      - /resources/thirdparty/travi-ui/js/dialog/buttons.js
    cssDependencies:
      - /resources/thirdparty/travi-styles/css/travi-form.css

carousel:
  cssDependencies:
    - /resources/css/pages/gallery/carousel.css
  large:
    local: /resources/js/photos/carousel.js

previewPane:
  large:
    local: /resources/js/photos/previewPane.js
    jsDependencies:
      - lightbox
    clientTemplates:
      previewPane: /resources/templates/previewPane.tmpl

thumbnails:
  local: /resources/js/photos/thumbnails.js
  cssDependencies:
    - /resources/css/pages/gallery/thumbnails.css
  jsDependencies:
    - framework
    - template
  clientTemplates:
    thumbnail: /resources/templates/thumbnail.tmpl

videoPlayer:
  local: /resources/js/video/player.js
  jsDependencies:
    - http://cdn.sublimevideo.net/js/ws9xvgbm.js
    - template
  clientTemplates:
    videoStage: /resources/templates/videoStage.tmpl

gallery:
  jsDependencies:
      - thumbnails
  large:
    local: /resources/js/photos/gallery.js
    jsDependencies:
      - events
      - carousel
      - videoPlayer
      - previewPane
      - reflection

#-------Form--------
richTextArea:
  local: /resources/thirdparty/travi-ui/js/form/richText.js
  jsDependencies:
    - wymEditor
    - wymEditor-fullScreen
    - framework

datePicker:
  local: /resources/thirdparty/travi-ui/js/form/date.js
  jsDependencies:
    - jqueryUi

buttons:
  local: /resources/thirdparty/travi-ui/js/form/buttons.js
  jsDependencies:
    - jqueryUi
    - framework

#=======jQuery======
jquery:
  local: /resources/thirdparty/jquery/jquery.js
  cdn: "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
  plugins:

    #------jQuery UI-----
    jqueryUi:
      local: /resources/thirdparty/jquery-ui/jquery-ui.js
      cssDependencies:
        - jqueryUiTheme

    #------jQuery Plug-ins------

    ajaxForm:
      local: /resources/thirdparty/jquery-form/jquery.form.js

    equalizeBottoms:
      local: /resources/thirdparty/jquery-equalizebottoms/jquery.ba-equalizebottoms.js

    lightbox:
      local: "/resources/shared/thirdparty/jquery/plugins/lightbox/jquery.lightbox.js"
      cssDependencies:
        - "/resources/shared/thirdparty/jquery/plugins/lightbox/css/jquery.lightbox.css"

    pxem:
      local: "/resources/shared/thirdparty/jquery/plugins/pxem/jquery.pxem.js"

    jsRender:
      local: "/resources/thirdparty/jsrender/jsrender.js"

    validation:
      local: "/resources/thirdparty/jquery.validation/jquery.validate.js"
      cssDependencies:
        - jqueryUiTheme

    wymEditor:
      local: /resources/thirdparty/wymeditor/jquery.wymeditor.js
      cssDependencies:
        - /resources/thirdparty/wymeditor/skins/silver/skin.css
      jsDependencies:
        - /resources/thirdparty/jquery-migrate/jquery-migrate.js
      plugins:
        wymEditor-fullScreen:
          local: /resources/thirdparty/wymeditor/plugins/fullscreen/jquery.wymeditor.fullscreen.js

#=====Third Party JavaScript=====
reflection:
  local: /resources/shared/thirdparty/reflection/reflection.js

instant:
  local: /resources/shared/thirdparty/instant/instant.js

moment:
  local: /resources/thirdparty/moment/moment.js

amplify:
  local: /resources/thirdparty/amplify/amplify.core.js
