#=======Framework Components=======
travi:
  local: /resources/thirdparty/travi-core/js/travi.js
  jsDependencies:
    - jquery

framework:
  local: /resources/thirdparty/travi-core/js/travi/framework.js
  jsDependencies:
    - dependencyLoader
    - events
    - enhancements

dependencyLoader:
  local: /resources/thirdparty/travi-core/js/travi/dependencies/loader.js
  jsDependencies:
    - travi

events:
  local: /resources/thirdparty/travi-core/js/travi/events.js
  jsDependencies:
    - travi
    - amplify

enhancements:
  local: /resources/thirdparty/travi-core/js/travi/enhancements.js
  jsDependencies:
    - template
    - cookieUtil
    - locationUtil
  clientTemplates:
    chooseEnhancement: /resources/thirdparty/travi-core/templates/enhancementVersion.tmpl

template:
  local: /resources/thirdparty/travi-core/js/travi/templates.js
  jsDependencies:
    - jsRender

pagination:
  local: /resources/thirdparty/travi-core/js/travi/pagination.js
  jsDependencies:
    - events

entityList:
  local: /resources/thirdparty/travi-core/js/travi/framework/entityList.js
  jsDependencies:
    - jqueryUi
    - ajaxForm
    - framework
    - pagination
  cssDependencies:
    - /resources/shared/css/travi-entities.css
  clientTemplates:
    update-item: /resources/templates/admin/update-item.tmpl

cookieUtil:
  local: /resources/thirdparty/travi-core/js/travi/cookies.js

locationUtil:
  local: /resources/thirdparty/travi-core/js/travi/location.js

carousel:
  cssDependencies:
    - /resources/css/pages/gallery/carousel.css
  large:
    local: /resources/js/photos/carousel.js

previewPane:
  large:
    local: /resources/js/photos/previewPane.js
    clientTemplates:
      previewPane: /resources/templates/previewPane.tmpl

thumbnails:
  local: /resources/js/photos/thumbnails.js
  cssDependencies:
    - /resources/css/pages/gallery/thumbnails.css
  jsDependencies:
    - framework
    - template
  clientTemplates:
    thumbnail: /resources/templates/thumbnail.tmpl

videoPlayer:
  local: /resources/js/video/player.js
  jsDependencies:
    - http://cdn.sublimevideo.net/js/ws9xvgbm.js
    - template
  clientTemplates:
    videoStage: /resources/templates/videoStage.tmpl

gallery:
  jsDependencies:
      - thumbnails
  large:
    local: /resources/js/photos/gallery.js
    jsDependencies:
      - events
      - carousel
      - videoPlayer
      - previewPane
      - lightbox
      - reflection

#=======jQuery======
jquery:
  local: /resources/thirdparty/jquery/jquery.js
  cdn: "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
  plugins:

    #------jQuery UI-----
    jqueryUi:
      local: /resources/thirdparty/jquery-ui/jquery-ui.js
      cssDependencies:
        - jqueryUiTheme

    #------jQuery Plug-ins------

    ajaxForm:
      local: /resources/shared/thirdparty/jquery/plugins/ajaxForm/jquery.form.js

    equalizeBottoms:
      local: /resources/shared/thirdparty/jquery/plugins/equalizeBottoms/jquery.equalizebottoms.js

    formAlign:
      local: "/resources/shared/thirdparty/jquery/plugins/formAlign/jquery.formAlign.js"

    jcarousel:
      local: "/resources/shared/thirdparty/jquery/plugins/jcarousel/jquery.jcarousel.js"
      cssDependencies:
        - "/resources/shared/thirdparty/jquery/plugins/jcarousel/jquery.jcarousel.css"
        - "jcarsouselSkin"

    lightbox:
      local: "/resources/shared/thirdparty/jquery/plugins/lightbox/jquery.lightbox.js"
      cssDependencies:
        - "/resources/shared/thirdparty/jquery/plugins/lightbox/css/jquery.lightbox.css"

    pxem:
      local: "/resources/shared/thirdparty/jquery/plugins/pxem/jquery.pxem.js"

    jsRender:
      local: "/resources/shared/thirdparty/jquery/plugins/template/jsrender.js"

    validation:
      local: "/resources/shared/thirdparty/jquery/plugins/validation/jquery.validate.min.js"
      cssDependencies:
        - "jqueryUiTheme"

    wymEditor:
      local: "/resources/shared/thirdparty/jquery/plugins/wymeditor/jquery.wymeditor.js"
      plugins:
        wymEditor-fullScreen:
          local: "/resources/shared/thirdparty/jquery/plugins/wymeditor/plugins/fullscreen/jquery.wymeditor.fullscreen.js"

#=====Third Party JavaScript=====
reflection:
  local: /resources/shared/thirdparty/reflection/reflection.js

instant:
  local: /resources/shared/thirdparty/instant/instant.js

moment:
  local: /resources/thirdparty/moment/moment.js

amplify:
  local: /resources/shared/thirdparty/amplify/amplify.core.js
