#=======Framework Components=======
framework:
  local: /resources/thirdparty/travi-core/dist/travi-core.min.js
  jsDependencies:
    - jquery
    - amplify
    - jsRender
  clientTemplates:
    chooseEnhancement: /resources/thirdparty/travi-core/templates/enhancementVersion.tmpl

pagination:
  local: /resources/thirdparty/travi-ui/js/pagination.js
  jsDependencies:
    - framework

dialog:
  local: /resources/thirdparty/travi-ui/dist/dialog.min.js
  jsDependencies:
    - framework
    - jqueryUi
    - form

entityList:
  local: /resources/thirdparty/travi-ui/js/entityList/pagination.js
  jsDependencies:
    - framework
    - ajaxForm
    - pagination
  cssDependencies:
    - /resources/thirdparty/travi-styles/dist/css/entities/travi-entities.css
  clientTemplates:
    update-item: /resources/thirdparty/travi-core/templates/entity-item.tmpl
  large:
    local: /resources/thirdparty/travi-ui/js/entityList/pagination.js
    jsDependencies:
      - dialog
      - /resources/thirdparty/travi-ui/js/entityList/updates.js

carousel:
  large:
    local: /resources/thirdparty/travi.org-theme/js/photos/carousel.js

previewPane:
  large:
    local: /resources/thirdparty/travi.org-theme/js/photos/previewPane.js
    jsDependencies:
      - lightbox

thumbnails:
  local: /resources/thirdparty/travi.org-theme/js/photos/thumbnails.js
  jsDependencies:
    - framework
  clientTemplates:
    thumbnail: /resources/thirdparty/travi.org-theme/templates/thumbnail.tmpl

videoPlayer:
  local: /resources/thirdparty/travi.org-theme/js/video/player.js
  jsDependencies:
    - http://cdn.sublimevideo.net/js/ws9xvgbm.js
  clientTemplates:
    videoStage: /resources/thirdparty/travi.org-theme/templates/videoStage.tmpl

gallery:
  jsDependencies:
    - thumbnails
  cssDependencies:
    - /resources/thirdparty/travi.org-theme/dist/css/gallery/gallery.css
  large:
    local: /resources/thirdparty/travi.org-theme/js/photos/gallery.js
    jsDependencies:
      - carousel
      - videoPlayer
      - previewPane
      - reflection

#-------Form--------
form:
  local: /resources/thirdparty/travi-ui/dist/form.min.js
  cssDependencies:
    - /resources/thirdparty/travi-styles/dist/css/form/travi-form.css
  jsDependencies:
    - jqueryUi
    - wymEditor
    - wymEditor-fullScreen
    - framework

richTextArea:
  local: /resources/thirdparty/travi-ui/js/form/richText.js
  jsDependencies:
    - wymEditor
    - wymEditor-fullScreen
    - framework

datePicker:
  local: /resources/thirdparty/travi-ui/js/form/date.js
  jsDependencies:
    - jqueryUi
    - framework

buttons:
  local: /resources/thirdparty/travi-ui/js/form/buttons.js
  jsDependencies:
    - jqueryUi
    - framework

validation:
  local: /resources/thirdparty/travi-ui/js/form/validation/active.js
  jsDependencies:
    - framework
    - jqueryValidation
  cssDependencies:
    - /resources/thirdparty/travi-styles/dist/css/form/travi-form.css

#=======jQuery======
jquery:
  local: /resources/thirdparty/jquery/jquery.js
  cdn: "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
  plugins:

    #------jQuery UI-----
    jqueryUi:
      local: /resources/thirdparty/jquery-ui/jquery-ui.js
      cssDependencies:
        - jqueryUiTheme

    #------jQuery Plug-ins------

    ajaxForm:
      local: /resources/thirdparty/jquery-form/jquery.form.js

    equalizeBottoms:
      local: /resources/thirdparty/jquery-equalizebottoms/jquery.ba-equalizebottoms.js

    lightbox:
      local: /resources/thirdparty/travi.org-theme/thirdparty/lightbox/jquery.lightbox.js
      cssDependencies:
        - /resources/thirdparty/travi.org-theme/thirdparty/lightbox/css/jquery.lightbox.css

    jsRender:
      local: "/resources/thirdparty/jsrender/jsrender.js"

    jqueryValidation:
      local: /resources/thirdparty/jquery.validation/jquery.validate.js
      cssDependencies:
        - jqueryUiTheme

    wymEditor:
      local: /resources/thirdparty/wymeditor/jquery.wymeditor.js
      cssDependencies:
        - /resources/thirdparty/wymeditor/skins/silver/skin.css
      jsDependencies:
        - /resources/thirdparty/jquery-migrate/jquery-migrate.js
      plugins:
        wymEditor-fullScreen:
          local: /resources/thirdparty/wymeditor/plugins/fullscreen/jquery.wymeditor.fullscreen.js

#=====Third Party JavaScript=====
reflection:
  local: /resources/thirdparty/travi.org-theme/thirdparty/reflection/reflection.js

instant:
  local: /resources/shared/thirdparty/instant/instant.js

moment:
  local: /resources/thirdparty/moment/moment.js

amplify:
  local: /resources/thirdparty/amplify/amplify.core.js
