#=======Framework Components=======
framework:
  local: "/resources/shared/js/travi.js"
  jsDependencies:
    - "jquery"

entityList:
  local: "/resources/shared/js/list/entityList.js"
  jsDependencies:
    - "jqueryUi"
    - "ajaxForm"
    - "framework"
  cssDependencies:
    - "/resources/shared/css/travi.entities.css"

cookieUtil:
  local: "/resources/shared/js/cookies/cookies.js"
  jsDependencies:
    - "framework"

gallery:
  local: "/resources/js/gallery.js"
  jsDependencies:
    - "lightbox"
    - "jcarousel"
    - "urlParser"
    - "reflection"
  cssDependencies:
    - "/resources/css/pages/gallery.dev.css"

#=======jQuery======
jquery:
  local: "/resources/shared/js/jquery/jquery.js"
  cdn: "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
  plugins:

    #------jQuery UI-----
    jqueryUi:
      local: "/resources/shared/js/jquery/ui/jquery-ui.js"
      cssDependencies:
        - "jqueryUiTheme"

    #------jQuery Plug-ins------

    ajaxForm:
      local: "/resources/shared/js/jquery/plugins/ajaxForm/jquery.form.js"

    equalizeBottoms:
      local: "/resources/shared/js/jquery/plugins/equalizeBottoms/jquery.equalizebottoms.js"

    formAlign:
      local: "/resources/shared/js/jquery/plugins/formAlign/jquery.formAlign.js"

    jcarousel:
      local: "/resources/shared/js/jquery/plugins/jcarousel/jquery.jcarousel.js"
      cssDependencies:
        - "/resources/shared/js/jquery/plugins/jcarousel/jquery.jcarousel.css"
        - "jcarsouselSkin"

    lightbox:
      local: "/resources/shared/js/jquery/plugins/lightbox/jquery.lightbox.js"
      cssDependencies:
        - "/resources/shared/js/jquery/plugins/lightbox/css/jquery.lightbox.css"

    pxem:
      local: "/resources/shared/js/jquery/plugins/pxem/jquery.pxem.js"

    template:
      local: "/resources/shared/js/jquery/plugins/template/jquery.tmpl.js"

    urlParser:
      local: "/resources/shared/js/jquery/plugins/url/jquery.url.js"

    validation:
      local: "/resources/shared/js/jquery/plugins/validation/jquery.validate.min.js"
      cssDependencies:
        - "jqueryUiTheme"

    wymEditor:
      local: "/resources/shared/js/jquery/plugins/wymeditor/jquery.wymeditor.js"
      plugins:
        wymEditor-fullScreen:
          local: "/resources/shared/js/jquery/plugins/wymeditor/plugins/fullscreen/jquery.wymeditor.fullscreen.js"

#=====Third Party JavaScript=====
reflection:
  local: "/resources/shared/js/reflection/reflection.js"

instant:
  local: "/resources/shared/js/instant/instant.js"

pngFix:
  local: "/resources/shared/js/pngFix/DD_belatedPNG.js"

dateFormat:
  local: "/resources/shared/js/date/date.format.js"
