<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/objects/content/navigation/navigation.class.php';

/**
 * Test class for NavigationObject.
 * Generated by PHPUnit on 2011-01-15 at 11:50:41.
 */
class NavigationObjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var NavigationObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NavigationObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testAddSection()
    {
        $title = 'title';
        $content = 'content';

        $this->object->addSection($title, $content);

        $this->assertSame(array($title => $content), $this->object->getSections());
    }

    public function testSetSection()
    {
        $title = 'title';
        $content = 'content';

        $this->object->setSection($title, $content);

        $this->assertSame(array($title => $content), $this->object->getSections());
    }

    public function testGetSection()
    {
        $title = 'title';
        $content = 'content';

        $this->object->setSection($title, $content);

        $this->assertSame($content, $this->object->getSection($title));
    }

    public function testAddSectionContent()
    {
        $title = 'title';
        $content = 'content';

        $this->object->addSectionContent($title, $content);

        $this->assertSame(array($title => $content), $this->object->getSections());
    }

    public function testAddSectionContentLinks()
    {
        $title = 'title';
        $links = array('link1', 'link2');

        $this->object->addSectionContentLinks($title, $links);

        $this->assertSame(array($title => $links), $this->object->getSections());
    }

    public function testSectionTemplate()
    {
        $template = 'template';

        $this->object->setSectionTemplate($template);
        $this->assertSame($template, $this->object->getSectionTemplate());
    }
}
?>
