<?php
require_once 'PHPUnit/Autoload.php';

require_once dirname(__FILE__).'/../../../../../src/components/form/FieldSet.php';

/**
 * Test class for FieldSet.
 * Generated by PHPUnit on 2011-01-25 at 20:14:27.
 */
class FieldSetTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FieldSet
     */
    protected $fieldSet;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $options = array();
        $options['legend'] = 'legend';

        $this->fieldSet = new FieldSet($options);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetLegend()
    {
        $this->assertSame('legend', $this->fieldSet->getLegend());
    }
}
?>
