<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/src/components/form/FieldSet.php';

/**
 * Test class for FieldSet.
 * Generated by PHPUnit on 2011-01-25 at 20:14:27.
 */
class FieldSetTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FieldSet
     */
    protected $fieldSet;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $options = array();
        $options['legend'] = 'legend';
//        $options['fields'] = array('field1', 'field2', 'field3');

        $this->fieldSet = new FieldSet($options);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetLegend()
    {
        $this->assertSame('legend', $this->fieldSet->getLegend());
    }

    public function testAddField()
    {
        $this->fieldSet->addField('field');

        $this->assertSame(array('field'), $this->fieldSet->getFields());
    }

    /**
     * @todo Implement testGetValidations().
     */
    public function testGetValidations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testContains().
     */
    public function testContains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetDependencies().
     */
    public function testGetDependencies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
