<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/src/components/form/Form.php';
require_once '/Users/travi/development/include/php/framework/src/components/form/FieldSet.php';
require_once '/Users/travi/development/include/php/framework/src/components/form/inputs/TextInput.php';

/**
 * Test class for Form.
 * Generated by PHPUnit on 2011-01-25 at 18:34:44.
 */
class FormTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Form
     */
    protected $form;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $options = array();
        $options['name'] = 'name';
        $options['action'] = 'action';

        $this->form = new Form($options);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetName()
    {
        $this->assertSame('name', $this->form->getName());
    }

    public function testGetMethodDefault()
    {
        $this->assertSame('post', $this->form->getMethod());
    }

    public function testGetMethodOverride()
    {
        $this->form->setMethod('method');
        $this->assertSame('method', $this->form->getMethod());
    }

    public function testGetAction()
    {
        $this->assertSame('action', $this->form->getAction());
    }

    public function testGetEncType()
    {
        $this->assertSame(null, $this->form->getEncType());
    }

    /**
     * @todo Implement testGetEncTypeFileUpload().
     */
    public function testGetEncTypeFileUpload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetFieldsets().
     */
    public function testGetFieldsets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    public function testFormAcceptsFieldSets()
    {
        $fieldSet = new FieldSet('fieldset');

        $this->form->addFormElement($fieldSet);

        $this->assertSame(array($fieldSet), $this->form->getFormElements());
    }

    public function testFormAcceptsFields()
    {
        $anyField = $this->getMock('TextInput');

        $this->form->addFormElement($anyField);

        $this->assertSame(array($anyField), $this->form->getFormElements());
    }

    /**
     * @todo Implement testContains().
     */
    public function testContains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    public function testGetDependencies()
    {
        $validations = array('required');

        $anyField = $this->getMock('TextInput');
        $anyField->expects($this->any())
                ->method('getValidations')
                ->will($this->returnValue($validations));

        $this->form->addFormElement($anyField);

        $this->assertSame(array(    'scripts'       => array('formAlign', 'validation'),
                                    'jsInits'       => array("$('form[name=\"name\"]').alignFields();"),
                                    'styles'        => array('/resources/shared/css/travi.form.css'),
                                    'validations'   => $validations),
            $this->form->getDependencies());
    }
}
?>
