<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/src/components/form/Form.php'; 

/**
 * Test class for Form.
 * Generated by PHPUnit on 2011-01-25 at 18:34:44.
 */
class FormTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Form
     */
    protected $form;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $options = array();
        $options['name'] = 'name';
        $options['action'] = 'action';

        $this->form = new Form($options);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetName()
    {
        $this->assertSame('name', $this->form->getName());
    }

    public function testGetMethodDefault()
    {
        $this->assertSame('post', $this->form->getMethod());
    }

    public function testGetMethodOverride()
    {
        $this->form->setMethod('method');
        $this->assertSame('method', $this->form->getMethod());
    }

    public function testGetAction()
    {
        $this->assertSame('action', $this->form->getAction());
    }

    public function testGetEncType()
    {
        $this->assertSame(null, $this->form->getEncType());
    }

    /**
     * @todo Implement testGetEncTypeFileUpload().
     */
    public function testGetEncTypeFileUpload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetFieldsets().
     */
    public function testGetFieldsets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    public function testAddFieldset()
    {
        $this->form->addFieldset('fieldset');

        $this->assertSame(array('fieldset'), $this->form->getFieldsets());
    }

    /**
     * @todo Implement testCloseFieldset().
     */
    public function testCloseFieldset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    public function testAddField()
    {
        $this->form->addField('field');

        $this->assertSame(array('field'), $this->form->getFieldsets());
    }

    /**
     * @todo Implement testContains().
     */
    public function testContains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetInnerValidations().
     */
    public function testGetInnerValidations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetDependencies().
     */
    public function testGetDependencies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
