<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/src/components/form/NoteArea.php';

/**
 * Test class for NoteArea.
 * Generated by PHPUnit on 2011-01-26 at 20:43:09.
 */
class NoteAreaTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var NoteArea
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NoteArea(array('label' => 'label', 'content' => 'content'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testDefaultInit()
    {
        $this->assertSame('label', $this->object->getLabel());
        $this->assertSame('content', $this->object->getContent());
        $this->assertSame('components/form/noteArea.tpl', $this->object->getTemplate());
    }

    public function testGetValidations()
    {
        $this->assertSame(array(), $this->object->getValidations());
    }
}
?>
