<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/src/components/form/RadioButtons.php';

/**
 * Test class for RadioButtons.
 * Generated by PHPUnit on 2011-02-19 at 20:07:20.
 */
class RadioButtonsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RadioButtons
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RadioButtons;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testDefaults()
    {
        $this->assertSame('components/form/choices.tpl', $this->object->getTemplate());
        $this->assertSame('radio', $this->object->getType());
        $this->assertSame('radioButton', $this->object->getClass());
    }

    public function testSetTemplate()
    {
        $this->object->setTemplate('template');

        $this->assertSame('template', $this->object->getTemplate());
    }
}
?>
