<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../src/components/form/SubmitButton.php';

/**
 * Test class for SubmitButton.
 * Generated by PHPUnit on 2011-01-26 at 17:58:55.
 */
class SubmitButtonTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SubmitButton
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SubmitButton;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testClassName()
    {
        $this->assertSame('submitButton', $this->object->getClass());
    }

    public function testAlternateClassName()
    {
        $button = new SubmitButton(array('class' => 'altSubmitButton'));
        $this->assertSame('altSubmitButton', $button->getClass());
    }

    /**
     * @todo Refactor SubmitButton to do this more intentionally.
     */
    public function testClassNameOutsideFieldSet()
    {
        $button = new SubmitButton(array('class' => 'submitButton outerButton'));
        $this->assertSame('submitButton outerButton', $button->getClass());

        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    public function testType()
    {
        $this->assertSame('submit', $this->object->getType());
    }

    public function testTemplate()
    {
        $this->assertSame('components/form/input.tpl', $this->object->getTemplate());
    }

    public function testGetJavaScripts()
    {
        $this->assertSame(array('jqueryUi'), $this->object->getJavaScripts());
    }

    public function testGetJsInits()
    {
        $this->assertSame(array('$("input[type=submit]").button()'), $this->object->getJsInits());
    }

    public function testGetName()
    {
        $this->assertSame('submit', $this->object->getName());
    }
}
?>
