<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/src/components/form/choices/CheckBoxes.php';

/**
 * Test class for CheckBoxes.
 * Generated by PHPUnit on 2011-02-19 at 20:13:33.
 */
class CheckBoxesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CheckBoxes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CheckBoxes;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testDefaults()
    {
        $this->assertSame('components/form/choices.tpl', $this->object->getTemplate());
        $this->assertSame('checkbox', $this->object->getType());
        $this->assertSame('checkbox', $this->object->getClass());
    }
}
?>
