<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/travi/development/include/php/framework/src/components/form/choices/SelectionBox.php';

/**
 * Test class for SelectionBox.
 * Generated by PHPUnit on 2011-02-13 at 13:23:17.
 */
class SelectionBoxTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SelectionBox
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SelectionBox;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }    

    public function testAddOption()
    {
        $this->object->addOption('option');

        $this->assertSame(array(array('option' => 'Select One', 'value' => '',
                'selected' => false, 'disabled' => false),
            array('option' => 'option', 'value' => '',
                'selected' => false, 'disabled' => false)),
            $this->object->getOptions());
    }

    public function testDefaultTemplate()
    {
        $this->assertSame('components/form/selectionBox.tpl', $this->object->getTemplate());
    }

    public function testSetTemplate()
    {
        $this->object->setTemplate('template');

        $this->assertSame('template', $this->object->getTemplate());
    }
}
?>
