<?php
require_once 'PHPUnit/Framework.php';

require_once '/home/travi/include/php/framework/src/controller/front/front.controller.php';
require_once '/home/travi/include/php/framework/src/http/Request.class.php';
require_once '/home/travi/include/php/framework/src/http/Response.class.php';

/**
 * Test class for FrontController.
 * Generated by PHPUnit on 2011-01-06 at 20:32:06.
 */
class FrontControllerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FrontController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FrontController;

        $config = array('docRoot' => dirname(__FILE__) . '/../../../../../../../wedding/doc_root/');

        $requestStub = $this->getMock('Request');
        $requestStub->expects($this->any())
                ->method('getController')
                ->will($this->returnValue('test'));
        $requestStub->expects($this->any())
                ->method('getAction')
                ->will($this->returnValue('index'));

        $responseStub = $this->getMock('Response', array('respond'));
//        $responseStub->expects($this->any())
//                ->method('getTitle')
//                ->will($this->returnValue('index'));

        $this->object->setConfig($config);
        $this->object->setRequest($requestStub);
        $this->object->setResponse($responseStub);
//        $this->object->setResponse(new Response($config));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testProcessRequest()
    {
        /** @var $response Response */
        $response = $this->object->processRequest();
        $this->assertSame($response->getTitle(), 'Test');
    }

    /**
     * @todo Implement testDoAction().
     */
    public function test404()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDoAction().
     */
    public function testRoot()
    {
        //This test may be more appropriate for the Request object

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
